endpoint:
  - wss://kusama.api.integritee.network
mock-signature-host: true
block: ${env.INTEGRITEE_KUSAMA_BLOCK_NUMBER}
db: ./integritee-kusama.db.sqlite
runtime-log-level: 5
wasm-override: /home/brenzi/integritee/parachain/target/release/wbuild/integritee-runtime/integritee_runtime.compact.compressed.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Council:
    Members:
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
  TechnicalCommittee:
    Members:
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
