endpoint: wss://polkadot-asset-hub-rpc.polkadot.io
mock-signature-host: true
#block: ${env.POLKADOT_ASSET_HUB_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5
wasm-override: asset_hub_polkadot_runtime_1.7.1_debug.compact.compressed.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
      -
        -
          - 14DXRZEfzojXowgGnamfGzTjnMERF9cVWRkdHHYQFiTsDiXB # sovereign account of IK on PAH
        - providers: 1
          data:
            free: 1000000000000000

  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[1337, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[21], { supply: 1000000000 }]]
  PolkadotXcm:
    SupportedVersion:
      - [[5, { V5: { parents: 2, interior: { X2: [{ GlobalConsensus: Kusama }, { Parachain: 1000 }] } } }], 5]
      - [[5, { V5: { parents: 1, interior: { X1: [{ Parachain: 1002 }] } } }], 5]
